{% set name = "rchitect" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/randy3k/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3323533ce857e218fb0e40a38d85035ab308e26e4ed8459aadbfb06e288e602c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cffi >=1.10.0
    - pip
    - python
    - setuptools >=61.0
    - wheel
  run:
    - cffi >=1.10.0
    - packaging >=23.0
    - python

test:
  imports:
    - rchitect
  commands:
    - pip check  # [not win]
  requires:
    - colorama  # [win]
    - pip

about:
  home: https://github.com/randy3k/rchitect
  summary: Mapping R API to Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randy3k
    - jdblischak
    - izahn
