{% set name = "rchitect" %}
{% set version = "0.3.32" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/randy3k/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 85dbfd71e7d72764d77786a49845085e64ae18b234c84162c72002475be5115f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi >=1.10.0
    - pip
    - pytest-runner
    - python
  run:
    - cffi >=1.10.0
    - python
    - six >=1.9.0

test:
  imports:
    - rchitect
    - rchitect.reticulate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/randy3k/rchitect
  summary: Mapping R API to Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randy3k
    - jdblischak
    - izahn
