{% set name = "rchitect" %}
{% set version = "0.3.40" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/randy3k/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d136a017e823a6ac1b68c44723f85d49e6c7f057eddec525335f09fb0e67c454

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cffi >=1.10.0
    - pip
    - pytest-runner
    - python
  run:
    - cffi >=1.10.0
    - python
    - six >=1.9.0

test:
  imports:
    - rchitect
    - rchitect.reticulate
  commands:
    - pip check  # [not win]
  requires:
    - colorama  # [win]
    - pip

about:
  home: https://github.com/randy3k/rchitect
  summary: Mapping R API to Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randy3k
    - jdblischak
    - izahn
