{% set name = "rchitect" %}
{% set version = "0.3.31" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rchitect-{{ version }}.tar.gz
  sha256: c6722c8fe533f7f27868ed8e8f7fc900b8e6ff55aaa3623631c99576fa392a08

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi >=1.10.0
    - pip
    - pytest-runner
    - python
  run:
    - cffi >=1.10.0
    - python
    - six >=1.9.0

test:
  imports:
    - rchitect
    - rchitect.reticulate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/randy3k/rchitect
  summary: Mapping R API to Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randy3k
    - jdblischak
    - izahn
